import = ["/Users/braidon/.config/alacritty/themes/themes/kanagawa_dragon.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Medium"

[font.italic]
family = "Hack Nerd Font"
style = "Regular"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[cursor]
thickness = 0.3

[cursor.style]
shape = "Beam"

[font.offset]
x = 0
# y = 4

[font.glyph_offset]
# y = 2


[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F12"

[window]
# decorations = "buttonless"
# family = "Hack Nerd Font"
dynamic_padding = true
opacity = 1

[window.padding]
x = 3
y = 3
