
[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[colors.bright]
red = "0xfe8019"
black = "0x665c54"
green = "0x3c3836"
yellow = "0x504945"
blue = "0xbdae93"
magenta = "0xebdbb2"
cyan = "0xd65d0e"
white = "0xfbf1c7"

[colors.normal]
black = "0x1d2021"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xd5c4a1"
