[[colors.indexed_colors]]
color = '0x2e3440'
index = 16

[[colors.indexed_colors]]
color = '0xcdcecf'
index = 17

[colors.primary]
background = '0x2e3440'
foreground = '0xcdcecf'
# Normal colors
[colors.normal]
black = '0x3b4252'
red = '0xbf616a'
green = '0xa3be8c'
yellow = '0xebcb8b'
blue = '0x81a1c1'
magenta = '0xb48ead'
cyan = '0x88c0d0'
white = '0xe5e9f0'
# Bright colors
[colors.bright]
black = '0x465780'
red = '0xd06f79'
green = '0xb1d196'
yellow = '0xf0d399'
blue = '0x8cafd2'
magenta = '0xc895bf'
cyan = '0x93ccdc'
white = '0xe7ecf4'
