[colors.primary]
background = '0x292b3c'
foreground = '0xf9fbff'

# PastelNight Alacritty Colors
# Default colors
[colors.normal]
black = '0x212230'
red = '0xfe4c4c'
green = '0x65ff91'
yellow = '0xffc965'
blue = '0x7fa7ff'
magenta = '0xb58cd8'
cyan = '0x7fe7ff'
white = '0xe6e7e9'

# Normal colors
[colors.bright]
black = '0x8d8e9a'
red = '0xfe4c4c'
green = '0x65ff91'
yellow = '0xffc965'
blue = '0x7fa7ff'
magenta = '0xb58cd8'
cyan = '0x7fe7ff'
white = '0xf9fbff'


# Bright colors
[[colors.indexed_colors]]
index = 16
color = '0xfe854c'

[[colors.indexed_colors]]
index = 17
color = '0xff8484'
