[colors.bright]
black = "#7e818b"
blue = "#9fc3e7"
cyan = "#99ddff"
green = "#44bb99"
magenta = "#ffaabb"
red = "#ee8866"
white = "#dddddd"
yellow = "#eedd88"

[colors.cursor]
cursor = "#ff218c"
text = "#fbfc86"

[colors.hints.start]
background = "#474e6c"
foreground = "#ffff00"

[colors.normal]
black = "#242837"
blue = "#70b2f3"
cyan = "#99ddff"
green = "#bbcc33"
magenta = "#ffaabb"
red = "#ee8866"
white = "#fdf1d4"
yellow = "#eedd88"

[colors.primary]
background = "#292d3e"
bright_foreground = "#fdf1d4"
foreground = "#cac0a9"

[colors.search.focused_match]
background = "#72aa00"
foreground = "#fbfc86"

[colors.search.matches]
background = "#5e81ac"
foreground = "#f8f8f8"

[colors.selection]
background = "#474e6c"
text = "#cac0a9"
